export const LOCAL_BUCKS_REWARDS = {
  // Buyer rewards
  SIGNUP: 10,
  VERIFY_PHONE: 5,
  VERIFY_EMAIL: 5,
  FIRST_PURCHASE: 25,
  LEAVE_REVIEW: 5,
  REFER_FRIEND_SIGNUP: 20,
  SHARE_VENDOR: 10,
  JOIN_EVENT: 15,
  BIRTHDAY_BONUS: 25,
  WEEKLY_LOGIN_STREAK: 5,

  // Vendor rewards
  COMPLETE_PROFILE: 25,
  FIRST_LISTING: 10,
  FIRST_SALE: 50,
  FIVE_STAR_REVIEW: 20,
  REFER_VENDOR: 100,
  MILESTONE_10_SALES: 100,
  MILESTONE_50_SALES: 250,
  MILESTONE_100_SALES: 500,
  PREMIUM_SUBSCRIPTION: 50,
  HOST_EVENT: 200,
  CONNECT_STRIPE: 10,
  CONNECT_DOMAIN: 10,
  // @-tag a neighbor to a business (max 5 rewarded / rolling 24h, enforced in refer_to_vendor.sql)
  REFER_TO_BUSINESS: 5,
} as const

export const LOCAL_BUCKS_COSTS = {
  // Buyer spending
  BOOST_VENDOR_1_DAY: 50,
  SHARE_LISTING_BOOST: 25,
  SPOTLIGHT_POST: 75,
  SPONSOR_CATEGORY: 100,

  // Vendor spending
  BOOST_LISTING_1_DAY: 75,
  FEATURED_PROFILE_1_WEEK: 150,
  HIGHLIGHTED_LISTING: 50,
  PROMOTE_EVENT: 100,
  SPONSORED_POST: 75,
} as const

export type LocalBucksRewardKey = keyof typeof LOCAL_BUCKS_REWARDS
export type LocalBucksCostKey = keyof typeof LOCAL_BUCKS_COSTS
