import Link from "next/link";
import Logo from "@/components/Logo";

export const metadata = { title: "Privacy Policy — Everything Local" };

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-white">
      <nav className="border-b border-gray-100 px-6 py-4 flex items-center justify-between">
        <Link href="/"><Logo size="sm" /></Link>
        <Link href="/" className="text-sm text-gray-500 hover:text-gray-900">← Home</Link>
      </nav>
      <article className="max-w-3xl mx-auto px-6 py-16 prose prose-gray">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Privacy Policy</h1>
        <p className="text-gray-400 text-sm mb-10">Last updated: June 2026</p>

        {[
          { title: "Information we collect", body: "We collect information you provide directly (name, email, location, business details) and information generated by your use of the platform (listings viewed, messages sent, purchases made). We do not sell your personal data." },
          { title: "How we use your information", body: "We use your information to operate the marketplace, send transactional emails (booking confirmations, messages), improve the platform, and display relevant local content. We do not use your data for third-party advertising." },
          { title: "Information sharing", body: "We share your public profile and listing information with other users as part of the marketplace. Your contact information is only shared with businesses when you initiate a purchase or booking. We do not sell data to third parties." },
          { title: "Data security", body: "We use Supabase for data storage with row-level security policies. Passwords are hashed and never stored in plain text. All data is transmitted over HTTPS." },
          { title: "Cookies", body: "We use essential cookies for authentication and session management. We do not use tracking or advertising cookies." },
          { title: "Your rights", body: "You may request deletion of your account and data at any time by contacting hello@everythinglocal.org. We will process deletion requests within 30 days." },
          { title: "Contact", body: "Questions about this policy? Email us at hello@everythinglocal.org." },
        ].map((s) => (
          <div key={s.title} className="mb-8">
            <h2 className="text-lg font-bold text-gray-900 mb-2">{s.title}</h2>
            <p className="text-gray-500 leading-relaxed text-sm">{s.body}</p>
          </div>
        ))}
      </article>
      <footer className="border-t border-gray-100 py-8 px-6 text-center text-sm text-gray-400">
        <p>© 2026 Everything Local · <Link href="/terms" className="hover:text-gray-600">Terms</Link> · <Link href="/contact" className="hover:text-gray-600">Contact</Link></p>
      </footer>
    </main>
  );
}
